Repository sablier-labs/v2-periphery, pull requests merged in 2023-12, with the labels that each got.

#227 Use safeTransferFrom in _handleTransfer function
  src/SablierV2Batch.sol
  test/utils/Precompiles.sol
Labels: enhancement

#229 Polish deploy-multi-chain script
  .env.example
  script/DeployDeterministicProtocol2.s.sol
  script/DeployProtocol2.s.sol
  shell/deploy-multi-chains.sh
Labels: enhancement

#235 docs: add guidelines for fork testing
  CONTRIBUTING.md
Labels: documentation

#244 build: bump solc and v2 core
  CHANGELOG.md
  foundry.toml
  package.json
  pnpm-lock.yaml
  test/fork/Fork.t.sol
  test/utils/Precompiles.sol
Labels: dependencies

#240 Use array to create deployment command
  shell/deploy-multi-chains.sh
Labels: bug, priority2

#246 build: install deps in prepack
  package.json
Labels: enhancement

#248 refactor: reorder struct fields
  src/types/DataTypes.sol
  test/utils/Precompiles.sol
Labels: enhancement
